from __future__ import annotations

from typing import Any


CATEGORY_TEMPLATES: dict[str, dict[str, Any]] = {
    "car accessories": {
        "evidence_thresholds": {
            "sold": 5,
            "active": 5,
            "suppliers": 2,
            "competitors": 3,
            "supporting": 2,
        },
        "required_evidence": [
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "suggested_keywords": {
            "ebay_sold": ["car seat gap organizer", "car side pocket storage"],
            "ebay_active": ["car seat gap organizer", "car storage accessory"],
            "mercari": ["car organizer", "car accessory"],
            "supplier": ["car seat gap storage box", "auto side organizer"],
        },
        "research_tasks": [
            "Confirm dimensions",
            "Check universal fit claims",
            "Avoid mechanical or safety-critical parts",
            "Check installation photos",
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "supplier_questions": [
            "What are the exact dimensions?",
            "Does the packaging include any logo?",
            "What is the product weight?",
            "Can you provide real install photos?",
            "What is the shipping cost for 5 units?",
        ],
        "red_flags": ["airbag", "seatbelt", "brake", "engine", "electrical", "battery"],
        "listing_angles": [
            "keeps car organized",
            "prevents items falling",
            "easy installation",
            "universal fit",
            "2-pack bundle",
        ],
        "category_warnings": [
            "Confirm this is not a safety-critical automotive part.",
            "Verify the fitment claim before buying any samples.",
        ],
    },
    "desk accessories": {
        "evidence_thresholds": {
            "sold": 5,
            "active": 5,
            "suppliers": 2,
            "competitors": 3,
            "supporting": 2,
        },
        "required_evidence": [
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "suggested_keywords": {
            "ebay_sold": ["desk cable clips", "desk organizer"],
            "ebay_active": ["desk organizer", "desk accessory"],
            "mercari": ["desk cable clip", "desktop organizer"],
            "supplier": ["desk accessory", "cable clip organizer"],
        },
        "research_tasks": [
            "Check bundle potential",
            "Check size and dimensions",
            "Check whether competitors use real photos",
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "supplier_questions": [
            "Can you confirm the material?",
            "What are the exact dimensions?",
            "Can you send real photos?",
            "Is the product stackable or bundle-friendly?",
            "What is the shipping cost for 5 units?",
        ],
        "red_flags": ["electrical", "fragile", "branded", "powered"],
        "listing_angles": [
            "cleans up desk clutter",
            "boosts productivity",
            "small space solution",
            "aesthetic desk setup",
        ],
        "category_warnings": [
            "Competitor photo quality matters a lot in desk accessories.",
            "Bundle potential can change the economics quickly.",
        ],
    },
    "home organization": {
        "evidence_thresholds": {
            "sold": 5,
            "active": 5,
            "suppliers": 2,
            "competitors": 3,
            "supporting": 2,
        },
        "required_evidence": [
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "suggested_keywords": {
            "ebay_sold": ["drawer organizer", "storage solution"],
            "ebay_active": ["home organizer", "drawer divider"],
            "mercari": ["storage organizer", "drawer organizer"],
            "supplier": ["home organizer", "storage solution", "drawer organizer"],
        },
        "research_tasks": [
            "Check dimensions and material",
            "Check return risk",
            "Check bundle potential",
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "supplier_questions": [
            "What is the material?",
            "What are the exact dimensions?",
            "Can the item be bundled safely?",
            "Is it stackable or foldable?",
            "What is the shipping cost for 5 units?",
        ],
        "red_flags": ["food contact", "child safety", "electrical", "fragile"],
        "listing_angles": ["saves space", "neat home", "simple storage", "drawer organization"],
        "category_warnings": [
            "Look closely at dimensions and storage capacity claims.",
            "Home organization wins often come from bundle-friendly sets.",
        ],
    },
    "pet accessories": {
        "evidence_thresholds": {
            "sold": 5,
            "active": 5,
            "suppliers": 2,
            "competitors": 3,
            "supporting": 2,
        },
        "required_evidence": [
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "suggested_keywords": {
            "ebay_sold": ["pet hair remover", "pet grooming glove"],
            "ebay_active": ["pet accessory", "pet grooming tool"],
            "mercari": ["pet accessory", "pet hair remover"],
            "supplier": ["pet accessory", "pet grooming tool"],
        },
        "research_tasks": [
            "Check material safety notes",
            "Avoid medicine or supplement claims",
            "Check for ingestible/contact risk",
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "supplier_questions": [
            "What material is used?",
            "Is it safe for generic pet use?",
            "Can you confirm there are no medicinal claims?",
            "Is it washable or easy to clean?",
            "What is the shipping cost for 5 units?",
        ],
        "red_flags": ["medicine", "supplement", "prescription", "ingestible", "veterinary"],
        "listing_angles": [
            "makes pet care easier",
            "safe generic accessory",
            "simple cleanup",
            "washable",
        ],
        "category_warnings": [
            "Avoid ingestibles, medical claims, and prescription-adjacent products.",
            "Material safety and washability matter more than in many other categories.",
        ],
    },
    "travel accessories": {
        "evidence_thresholds": {
            "sold": 5,
            "active": 5,
            "suppliers": 2,
            "competitors": 3,
            "supporting": 2,
        },
        "required_evidence": [
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "suggested_keywords": {
            "ebay_sold": ["travel organizer", "packing cube"],
            "ebay_active": ["travel accessory", "packing organizer"],
            "mercari": ["travel organizer", "packing cube"],
            "supplier": ["travel accessory", "travel organizer", "packing cube"],
        },
        "research_tasks": [
            "Check compactness and weight",
            "Check bundle potential",
            "Check shipping risk",
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "supplier_questions": [
            "What is the product weight?",
            "Can it ship compactly?",
            "What are the exact dimensions?",
            "Is the packaging travel friendly?",
            "What is the shipping cost for 5 units?",
        ],
        "red_flags": ["battery", "electrical", "fragile", "liquid"],
        "listing_angles": ["travel convenience", "compact storage", "easy packing", "carry-on friendly"],
        "category_warnings": [
            "Compactness and weight matter more than raw cost here.",
            "Travel products often win when they solve one clear packing pain point.",
        ],
    },
    "creator tools": {
        "evidence_thresholds": {
            "sold": 5,
            "active": 5,
            "suppliers": 2,
            "competitors": 3,
            "supporting": 2,
        },
        "required_evidence": [
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "suggested_keywords": {
            "ebay_sold": ["creator tool", "content creator accessory"],
            "ebay_active": ["desk mount", "creator accessory"],
            "mercari": ["creator accessory", "desk mount"],
            "supplier": ["creator tool", "content creator accessory", "desk mount"],
        },
        "research_tasks": [
            "Check photo quality needs",
            "Check feature clarity",
            "Check bundle potential",
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "supplier_questions": [
            "Can you provide real photos?",
            "What are the exact features?",
            "What is the product weight?",
            "Does it require power or software compatibility?",
            "What is the shipping cost for 5 units?",
        ],
        "red_flags": ["electronics", "trademarked", "powered", "software"],
        "listing_angles": ["content creator utility", "desk-friendly setup", "simple workflow", "camera helper"],
        "category_warnings": [
            "Compatibility claims matter if the item attaches to phones or cameras.",
            "Photo quality and perceived utility are major purchase drivers.",
        ],
    },
    "small tools": {
        "evidence_thresholds": {
            "sold": 5,
            "active": 5,
            "suppliers": 2,
            "competitors": 3,
            "supporting": 2,
        },
        "required_evidence": [
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "suggested_keywords": {
            "ebay_sold": ["small tool", "hand tool"],
            "ebay_active": ["utility tool", "small workshop tool"],
            "mercari": ["hand tool", "utility tool"],
            "supplier": ["small tool", "utility tool", "hand tool"],
        },
        "research_tasks": [
            "Confirm material and dimensions",
            "Check if the tool is powered or mechanical",
            "Check use case clarity",
            "Add 5 sold eBay listings",
            "Add 5 active eBay listings",
            "Add 2 supplier sources",
        ],
        "supplier_questions": [
            "Is the tool powered?",
            "What is the exact material?",
            "What are the exact dimensions?",
            "Is this safety-critical or purely convenience-driven?",
            "What is the shipping cost for 5 units?",
        ],
        "red_flags": ["powered", "safety-critical", "mechanical", "electric"],
        "listing_angles": ["easy job completion", "small workshop helper", "time saver", "handy utility"],
        "category_warnings": [
            "Avoid safety-critical and powered tools unless you have strong evidence and compliance clarity.",
            "Utility tools can win on convenience and clear use cases.",
        ],
    },
}
